language: node_js

branches:
  only:
  - master

deploy:
  provider: npm
  email: $MDB_NPM_EMAIL
  api_key: $MDB_NPM_TOKEN

before-deploy:
- npm version patch
- declare -x VERSION=$(jq '.version' package.json)
- VERSION="${VERSION//\"}"
- echo $VERSION;

after_success:
- git add package.json
- git commit -m "[skip ci]"
- git push
- git tag $VERSION
- git push origin --tags

  