sudo: required
dist: trusty
language: node_js
node_js:
  - "node"

branches:
  only:
  - master

before_deploy:
- git remote set-url origin https://$MDB_GIT_USER:$MDB_GIT_TOKEN@github.com/matthewbill/nvoy.git
- git config --global push.default simple
- git config user.name "Travis CI"
- git config user.email "travis@travis-ci.org"
- npm config set git-tag-version=false # git-tag-version is false otherwise cause infinite loop

- npm version patch
- declare -x VERSION=$(jq '.version' package.json)
- VERSION="${VERSION//\"}"
- echo $VERSION;

deploy:
  provider: npm
  email: $MDB_NPM_EMAIL
  api_key: $MDB_NPM_TOKEN

after_deploy:
- git add package.json
- git commit -m "[skip ci]"
- git push
- git tag $VERSION
- git push --tags

  