sudo: required
dist: trusty
language: node_js
node_js:
  - "node"

addons:
  sonarcloud:
    organization: "matthewbill-github"
    token:
      secure: $SONAR_TOKEN

branches:
  only:
  - master

before_install:
# Setup
- sudo apt-get update
- sudo apt-get install -y jq
- pip install --upgrade --user awscli
- aws --version

script:
- npm test
- npm run lint
# Version
- npm config set git-tag-version=false # git-tag-version is false otherwise cause infinite loop
- npm version patch
- export VERSION=$(jq '.version' package.json)
- VERSION="${VERSION//\"}"
- echo $VERSION;
# Sonar
- mdb-bt sonar-update sonar-project.properties -v $VERSION -b master
- cat sonar-project.properties
- sonar-scanner

before_deploy:
# Git Configuration
- git checkout master
- git remote set-url origin https://$GIT_HUB_USER:$GIT_HUB_TOKEN@github.com/matthewbill/nvoy.git
- git config --global push.default simple
- git config user.name "Travis CI"
- git config user.email "travis@travis-ci.org"

deploy:
  provider: npm
  email: $MDB_NPM_EMAIL
  api_key: $MDB_NPM_TOKEN

after_deploy:
# Infrastructure
- echo Validating Cloud Formation Templates
- aws cloudformation validate-template --template-body file://scripts/deployment/infrastructure-template.json
- echo Deploying Infrastructure
- aws cloudformation deploy --stack-name nvoy --template-file ./scripts/deployment/infrastructure-template.json --no-fail-on-empty-changeset
# Update Repo
- git add package.json
- git commit -m "[skip ci]"
- git push
- git tag $VERSION
- git push --tags
# Docs
- npm run docs
- aws s3 rm s3://nvoy/current --recursive
- aws s3 cp ./docs s3://nvoy/current --recursive
- aws s3 cp ./docs s3://nvoy/$VERSION --recursive
