sudo: required
dist: trusty
language: node_js
node_js:
  - "node"

branches:
  only:
  - master

before_deploy:
- npm version patch
- declare -x VERSION=$(jq '.version' package.json)
- VERSION="${VERSION//\"}"
- echo $VERSION;

deploy:
  provider: npm
  email: $MDB_NPM_EMAIL
  api_key: $MDB_NPM_TOKEN

after_deploy:
- git config user.name "Travis CI"
- git config user.email "travis@travis-ci.org"
- git remote add deploy "https://$MDB_GIT_USER:$MDB_GIT_TOKEN@github.com/matthewbil/nvoy.git" &>/dev/null
- git add package.json
- git commit -m "[skip ci]"
- git push deploy master
- git tag $VERSION
- git push deploy master --tags

  