sudo: required
dist: trusty
language: node_js
node_js:
  - "node"

branches:
  only:
  - master

before_deploy:
- npm version patch
- declare -x VERSION=$(jq '.version' package.json)
- VERSION="${VERSION//\"}"
- echo $VERSION;

deploy:
provider: npm
email: $MDB_NPM_EMAIL
api_key: $MDB_NPM_TOKEN

after_success:
- git add package.json
- git commit -m "[skip ci]"
- git push
- git tag $VERSION
- git push origin --tags

  